forcegun = {
	name = "Force Gun",
	additiveReload = false,
	magSize = 100,
	maxAmmo = 3000,
	currAmmo = -1,
	currMag = -1,
	spread = 0,
	projectiles = 1,
	shotCooldownTime = 0,
	fullAuto = true,
	warmupTimeMax = 0,
	warmupWindDown = false,
	burstFireMax = 0,
	maxReloadTime = 2.5,
	minRndSpread = 1,
	maxRndSpread = 10,
	maxDistance = 100,
	hitForce = 10000,
	hitscanBullets = true,
	incendiaryBullets = false,
	explosiveBullets = false,
	explosiveBulletMinSize = 0.3,
	explosiveBulletMaxSize = 0.5,
	projectileBulletSpeed = 100,
	applyForceOnHit = true,
	softRadiusMin = 0,
	softRadiusMax = 0,
	mediumRadiusMin = 0,
	mediumRadiusMax = 0,
	hardRadiusMin = 0,
	hardRadiusMax = 0,
	sfx = { shot_loop = "sfx/forcegun_shot_loop.ogg", },
	sfxLength = { shot_start = 0},
	infinitePenetration = false,
	particlesEnabled = false,
}