holecutter = {
	name = "Hole Cutter",
	customProfile = false,
	additiveReload = false,
	magSize = 100,
	maxAmmo = 300,
	currAmmo = -1,
	spread = 0.05,
	projectiles = 10,
	shotCooldownTime = 0.05,
	fullAuto = true,
	warmupTimeMax = 0,
	warmupWindDown = false,
	burstFireMax = 0,
	maxReloadTime = 2.5,
	minRndSpread = 10,
	maxRndSpread = 10,
	maxDistance = 100,
	hitForce = 1000,
	hitscanBullets = true,
	incendiaryBullets = false,
	explosiveBullets = false,
	explosiveBulletMinSize = 0.3,
	explosiveBulletMaxSize = 0.5,
	projectileBulletSpeed = 80,
	applyForceOnHit = false,
	softRadiusMin = 3,
	softRadiusMax = 3,
	mediumRadiusMin = 3,
	mediumRadiusMax = 3,
	hardRadiusMin = 3,
	hardRadiusMax = 3,
	sfx = { shot_loop = "sfx/lasercutter_shot_loop.ogg", },
	sfxLength = { shot_start = 0},
	infinitePenetration = false,
	particlesEnabled = false,
}