railgun = {
	name = "Railgun",
	customProfile = false,
	additiveReload = false,
	magSize = 1,
	maxAmmo = 300,
	currAmmo = -1,
	spread = 0,
	projectiles = 1,
	shotCooldownTime = 0.01,
	fullAuto = false,
	warmupTimeMax = 4.5,
	warmupWindDown = false,
	burstFireMax = 0,
	maxReloadTime = 4,
	minRndSpread = 1,
	maxRndSpread = 10,
	maxDistance = 75,
	hitForce = 6000,
	hitscanBullets = true,
	incendiaryBullets = false,
	explosiveBullets = true,
	explosiveBulletMinSize = 0.5,
	explosiveBulletMaxSize = 0.5,
	projectileBulletSpeed = 5,
	applyForceOnHit = false,
	softRadiusMin = 3,
	softRadiusMax = 4,
	mediumRadiusMin = 2,
	mediumRadiusMax = 3,
	hardRadiusMin = 1,
	hardRadiusMax = 2,
	sfx = {warmup_start = "sfx/railgun_warmup.ogg", shot = "sfx/railgun_shot.ogg" },
	sfxLength = { warmup_start = 4.841 },
	infinitePenetration = true,
	bulletHealth = 0,
	projectileGravity = 0,
	drawProjectileLine = true,
	
	hitParticleSettings = {
		enabled = true,
		ParticleType = "smoke",
		ParticleTile = 0,
		lifetime = 5,
		ParticleColor = {1, 1, 1, 1, 1, 1},
		ParticleRadius = 	{ true, 0.5, 1, "linear", 0, 1},
		ParticleAlpha = 	{ false, 1, 1, "linear", 0, 1},
		ParticleGravity = 	{ false, 0, 0, "linear", 0, 1},
		ParticleDrag = 		{ false, 0, 0, "linear", 0, 1},
		ParticleEmissive = 	{ false, 0, 0, "linear", 0, 1},
		ParticleRotation = 	{ false, 0, 0, "linear", 0, 1},
		ParticleStretch = 	{ false, 0, 0, "linear", 0, 1},
		ParticleSticky = 	{ false, 0, 0, "linear", 0, 1},
		ParticleCollide = 	{ true, 1, 1, "linear", 0, 1},
	},

	shotSmokeParticleSettings = {
		enabled = true,
		ParticleType = "smoke",
		ParticleTile = 0,
		lifetime = 3,
		ParticleColor = {1, 1, 1, 0, 0, 0},
		ParticleRadius = 	{ true, 0.1, 0.3, "linear", 0, 1},
		ParticleAlpha = 	{ false, 1, 1, "linear", 0, 1},
		ParticleGravity = 	{ true, 0.4, 0.4, "linear", 0, 1},
		ParticleDrag = 		{ false, 0, 0, "linear", 0, 1},
		ParticleEmissive = 	{ false, 0, 0, "linear", 0, 1},
		ParticleRotation = 	{ false, 0, 0, "linear", 0, 1},
		ParticleStretch = 	{ false, 0, 0, "linear", 0, 1},
		ParticleSticky = 	{ false, 0, 0, "linear", 0, 1},
		ParticleCollide = 	{ true, 1, 1, "linear", 0, 1},
	},

	shotFireParticleSettings = {
		enabled = true,
		ParticleType = "plain",
		ParticleTile = 3,
		lifetime = 0.3,
		ParticleColor = {1, 0.75, 0.4, 0, 0, 0},
		ParticleRadius = 	{ true, 0.4, 0.2, "smooth", 0, 1},
		ParticleAlpha = 	{ false, 1, 1, "linear", 0, 1},
		ParticleGravity = 	{ false, 0, 0, "linear", 0, 1},
		ParticleDrag = 		{ false, 0, 0, "linear", 0, 1},
		ParticleEmissive = 	{ true, 1, 0, "smooth", 0, 1},
		ParticleRotation = 	{ false, 0, 0, "linear", 0, 1},
		ParticleStretch = 	{ true, 1, 0.3, "linear", 0, 1},
		ParticleSticky = 	{ false, 0, 0, "linear", 0, 1},
		ParticleCollide = 	{ true, 1, 1, "linear", 0, 1},
	},

	projectileParticleSettings = {
		enabled = true,
		ParticleType = "smoke",
		ParticleTile = 0,
		lifetime = 7,
		ParticleColor = {0, 1, 1, 0, 0, 0},
		ParticleRadius = 	{ true, 0.5, 0, "linear", 0, 1},
		ParticleAlpha = 	{ true, 1, 0, "linear", 0, 1},
		ParticleGravity = 	{ false, 1, 1, "linear", 0, 1},
		ParticleDrag = 		{ false, 0, 0, "linear", 0, 1},
		ParticleEmissive = 	{ true, 1, 1, "linear", 0, 1},
		ParticleRotation = 	{ false, 0, 0, "linear", 0, 1},
		ParticleStretch = 	{ true, 1, 0, "linear", 0, 1},
		ParticleSticky = 	{ false, 0, 0, "linear", 0, 1},
		ParticleCollide = 	{ false, 1, 1, "linear", 0, 1},
	},
}