railgun = {
	name = "Railgun",
	customProfile = false,
	additiveReload = false,
	magSize = 1,
	maxAmmo = 300,
	currAmmo = -1,
	spread = 0,
	projectiles = 1,
	shotCooldownTime = 0.01,
	fullAuto = false,
	warmupTimeMax = 4.5,
	warmupWindDown = false,
	burstFireMax = 0,
	maxReloadTime = 4,
	minRndSpread = 1,
	maxRndSpread = 10,
	maxDistance = 75,
	hitForce = 6000,
	hitscanBullets = true,
	incendiaryBullets = false,
	explosiveBullets = true,
	explosiveBulletMinSize = 0.5,
	explosiveBulletMaxSize = 0.5,
	projectileBulletSpeed = 5,
	applyForceOnHit = false,
	softRadiusMin = 3,
	softRadiusMax = 4,
	mediumRadiusMin = 2,
	mediumRadiusMax = 3,
	hardRadiusMin = 1,
	hardRadiusMax = 2,
	sfx = {warmup_start = "sfx/railgun_warmup.ogg", shot = "sfx/railgun_shot.ogg" },
	sfxLength = { warmup_start = 4.841 },
	infinitePenetration = true,
	particlesEnabled = true,
}